{{ $skillsDir := .agents.skills.dir }}
{{- if (dig "agents" "skills" "pocock" "enabled" false .) -}}
[pocock-grill]
	type = "archive"
	url = "https://github.com/mattpocock/skills/archive/main.tar.gz"
	exact = true
	include = ["skills-main/skills/productivity/grill-me/**"]
	stripComponents = 4
	targetPath = "{{$skillsDir}}/grill-me"

[pocock-handoff]
	type = "archive"
	url = "https://github.com/mattpocock/skills/archive/main.tar.gz"
	exact = true
	include = ["skills-main/skills/productivity/handoff/**"]
	stripComponents = 4
	targetPath = "{{$skillsDir}}/handoff"

[pocock-grilling]
	type = "archive"
	url = "https://github.com/mattpocock/skills/archive/main.tar.gz"
	exact = true
	include = ["skills-main/skills/productivity/grilling/**"]
	stripComponents = 4
	targetPath = "{{$skillsDir}}/grilling"

[pocock-grill-docs]
	type = "archive"
	url = "https://github.com/mattpocock/skills/archive/main.tar.gz"
	exact = true
	include = ["skills-main/skills/engineering/grill-with-docs/**"]
	stripComponents = 4
	targetPath = "{{$skillsDir}}/grill-with-docs"

[pocock-domain-modeling]
	type = "archive"
	url = "https://github.com/mattpocock/skills/archive/main.tar.gz"
	exact = true
	include = ["skills-main/skills/engineering/domain-modeling/**"]
	stripComponents = 4
	targetPath = "{{$skillsDir}}/domain-modeling"

{{ end -}}
{{- if (dig "agents" "skills" "superpowers" "enabled" false .) -}}
[superpowers]
	type = "archive"
	url = "https://github.com/obra/superpowers/archive/main.tar.gz"
	exact = true
	include = ["superpowers-main/skills/subagent-driven-development/**"]
	targetPath = "{{$skillsDir}}/subagent-driven-development"
	stripComponents = 3
{{ end -}}